// <copyright file="GeneratedCodeTests.cs" company="Palantir (Pty) Ltd">
// Copyright (c) Palantir (Pty) Ltd. All rights reserved.
// </copyright>

namespace Documentation.Analyser.Test.Property
{
    using Helpers;
    using Microsoft.CodeAnalysis;
    using Verifiers;
    using Xunit;

    /// <summary>
    /// test that generated code is ignored.
    /// </summary>
    public class GeneratedCodeTests
    {
        /// <summary>
        /// test generated code.
        /// </summary>
        [Fact]
        public void TestThatGeneratedCodeDoesNotTrigger()
        {
            var test = @"
//
// <auto-generated />
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;

namespace ConsoleApplication1
{
    class TypeName
    {
        public string VogonConstructorFleet { get; set; }
    }
}";
            var expected = new DiagnosticResult[] { };
            new DocumentationPropertyCodeFixVerifier().VerifyCSharpDiagnostic(test, expected);
        }
    }
}
